//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF_generator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Admission_Number { get; set; }
        public string Full_Name { get; set; }
        public string Nationality { get; set; }
        public string Mother_Tonguage { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Subcaste { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthDate_in_Words { get; set; }
        public string Birth_Place { get; set; }
    }
}
